---
kind: pipeline
name: default

steps:
  - name: download apks
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: original
        path: /tmp/original
    environment:
      PLAYSTORE_MAIL:
        from_secret: PLAYSTORE_MAIL
      AAS_TOKEN:
        from_secret: AAS_TOKEN
    commands:
      - docker build -t apk-downloader -f downloader/Dockerfile downloader
      - docker run -v /tmp/original:/output/ apk-downloader $PLAYSTORE_MAIL $AAS_TOKEN com.twitter.android /output/com.twitter.android.apk

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: original
    host:
      path: /tmp/docker/apk-repo/original
