kind: pipeline
type: docker
name: default

steps:
  - name: clean-downloader
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f
      - docker rm -f apk-downloader || true
      - docker rmi -f apk-downloader

  - name: build
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f downloader/Dockerfile --tag apk-downloader --force-rm
