---
kind: pipeline
name: default

steps:
  - name: download apks
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      PLAYSTORE_MAIL:
        from_secret: PLAYSTORE_MAIL
      AAS_TOKEN:
        from_secret: AAS_TOKEN
    commands:
      - docker build -t apk-downloader -f downloader/Dockerfile downloader
      - docker run -v /srv/docker/apk-repo/original:/output apk-downloader $PLAYSTORE_MAIL $AAS_TOKEN com.twitter.android /output/com.twitter.android.apk

  - name: update fdroid
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: private
        path: /private
      - name: original
        path: /original
    commands:
      - cp /original/*.apk /private/repo/
      - docker build -t apk-repo -f repo/Dockerfile repo
      - docker run -v /srv/docker/apk-repo/private:/fdroid repo update -c
      - docker run -v /srv/docker/apk-repo/private:/fdroid -v /srv/docker/apk-repo/public:/public repo deploy -v

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: original
    host:
      path: /srv/docker/apk-repo/original
  - name: private
    host:
      path: /srv/docker/apk-repo/private
